#!/bin/bash
#set -x
#set -v

PATH=/sbin:$PATH

source /etc/muggles/pinglogger_config

#( ping -c1 -w1 $remotepinguplink1 2>&1 | grep unreachable ) && ( echo no route; exit 0 )
( ping -c1 -w1 ${remote_ping_uplinkk_ip[0]} 2>&1 | grep unreachable ) && ( echo no route; exit 0 )
## this is a stupid hack. Fix logic later (see config file also)



## change web script so names and ips are the latest
for ((i=1; i<=$NUMBER_OF_UPLINKS; i++))
do
  farname=${remote_ping_uplinkk_name[i-1]}
  sed -i "s/^UPLINK${i}_FAR_NAME=.*$/UPLINK${i}_FAR_NAME=$farname/" $path_to_showcurrent

  nearip=${nearipk[i-1]}
  sed -i "s/^UPLINK${i}_NEAR_IP=.*/UPLINK${i}_NEAR_IP=$nearip/" $path_to_showcurrent
done


>$near_pings_log
>$remote_pings_log


while (true) do
  for ((i=1; i<=$NUMBER_OF_UPLINKS; i++))
  do
    ( echo -n "UPLINK${i}:$(date +%H:%M): " ; ping -i $ping_interval -q -W $ping_timeout -c $ping_count ${remote_ping_uplinkk_ip[i-1]} 2>&1 | sed -n 's/^.*, \(.*\) packet \(loss\).*/\1 lost/p' ) >> $remote_pings_log
    ( echo -n "UPLINK${i} bam: $(date +%H:%M): " ; ping -i $ping_interval -q -W $ping_timeout -c $ping_count ${nearipk[i-1]} 2>&1 | sed -n 's/^.*, \(.*\) packet \(loss\).*/\1 lost/p' ) >> $near_pings_log
  done
done 


