#!/bin/bash
#set -x
#set -v

PATH=/sbin:$PATH

source /etc/muggles/pinglogger_config

( ping -c1 -w1 $remotepinguplink1 2>&1 | grep unreachable ) && ( echo no route; exit 0 )

## change web script so names and ips are the latest
for i in `seq 1 $NUMBER_OF_UPLINKS`
do
  nameused=`eval echo '$''remotepingname'${i}`
  sed -i "s/^UPLINK${i}_FAR_NAME=.*$/UPLINK${i}_FAR_NAME=$nameused/" $path_to_showcurrent



  nearip=(eval echo '$'nearip${i})
  sed -i "s/^UPLINK${i}_NEAR_IP=.*/UPLINK${i}_NEAR_IP=$nearip/" $path_to_showcurrent
done


>$near_pings_log
>$remote_pings_log


while (true) do
  for i in `seq 1 $NUMBER_OF_UPLINKS`
  do
    ip=(eval echo '$'remotepinguplink${i})
    ( echo -n "UPLINK${i}:`date +%H:%M`: " ; ping -i $ping_interval -q -W $ping_timeout -c $ping_count $ip 2>&1 | sed -n 's/^.*, \(.*\) packet \(loss\).*/\1 lost/p' ) >> $remote_pings_log

    nearip=(eval echo '$'nearip${i})
    ( echo -n "UPLINK${i} bam: `date +%H:%M`: " ; ping -i $ping_interval -q -W $ping_timeout -c $ping_count $nearip 2>&1 | sed -n 's/^.*, \(.*\) packet \(loss\).*/\1 lost/p' ) >> $near_pings_log
  done
done 



